<?php

/**
 * @file
 * Api logging module.
 */

/**
 * Implements hook_cron().
 *
 * Controls the size of the api log table, paring it to 'api_logger_row_limit' messages.
 */
function bc_api_logger_cron() {
  // Cleanup the watchdog table.
  $row_limit = \Drupal::config('api_logger.settings')->get('row_limit');

  // For row limit n, get the wid of the nth row in descending wid order.
  // Counting the most recent n rows avoids issues with wid number sequences,
  // e.g. auto_increment value > 1 or rows deleted directly from the table.
  if ($row_limit > 0) {
    $connection = \Drupal::database();
    $min_row = $connection->select('api_log', 'l')
      ->fields('l', ['id'])
      ->condition('keep', 0)
      ->orderBy('id', 'DESC')
      ->range($row_limit - 1, 1)
      ->execute()->fetchField();

    // Delete all table entries older than the nth row, if nth row was found.
    if ($min_row) {
      $connection->delete('api_log')
        ->condition('id', $min_row, '<')
        ->condition('keep', 0)
        ->execute();
    }
  }
}
