# Schema for the configuration files of the api_logger module.
api_logger.settings:
  type: config_object
  label: 'API logging settings'
  mapping:
    row_limit:
      type: integer
      label: 'API log messages to keep'
